// This file will be generated by: npx supabase gen types typescript --project-id PROJECT_ID > src/types/database.ts
// For now, we'll use a placeholder type

export type Database = {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
  }
}
